model_type: vae
model_name: cat_vae

hid_dim: 2056
emd_dim: 512
coords_dim: 64
num_layer: 7
n_head: 4
dropout: 0.10
w: 0.0
ema_rate: 0.999
ema: False
var_type: fixedsmall
skips: [1, 3, 5, 6]
downsample: 1
obj_feature: 6
obj_feature_keys:
  - "normal"

latentD: 16
n_neurons: 256
pointnet_hc: 64

robustkl: True
kl_coef: 0.05