model_type: vae
model_name: point_vae
feat_dim: ${model.feat_dim}
glob_feat_dim: 512
glob_obj_feat_dim: 1024
latent:
  hd: 512
  dim: 256

encoder:
  hd: 512

obj_encoder:
  hd: 128

decoder:
  hd: 512