model_type: vae
model_name: point_vae
feat_dim: ${ae.feat_dim}
ae_pretrained_weight: logs/wandb_logs/LG3DContact/GRIDAE-128v1/checkpoints/last.ckpt
ae_freeze_until_epoch: 10  # Epoch to unfreeze pretrained autoencoder weights for end-to-end training
glob_feat_dim: 512
glob_obj_feat_dim: 128
latent:
  hd: 256
  dim: 256

encoder:
  hd: 256

obj_encoder:
  hd: 128

decoder:
  hd: 256