name: recon_vae_${hand_ae.latent_dim}latent
input_channel: 3
latent_dim: 16
hidden_dim: 64
feat_dim: 1024

mano_root: ${data.mano_root}

pretrained_weight: logs/checkpoints/handvae/${hand_ae.latent_dim}latent/best.ckpt
