name: GRIDAEResidualv2
in_dim: ${add:1,${data.hand_cse_dim}}
kernel_size: ${msdf.kernel_size}
h_dims: 
  - 64
  - 128
  - 256
feat_dim: 256
res_expansion: 1
n_res_layers: 2

obj_feat_dim: 64
obj_h_dims:
  - 16
  - 32
  - 64
obj_res_expansion: 2
obj_n_res_layers: 2
out_dim: ${add:1,${data.hand_cse_dim}}
obj_in_dim: 1

use_noncontact_grids: true
# pretrained_weight: logs/checkpoints/gridae/128latent/best-epoch=16-val/total_loss=0.0948.ckpt
pretrained_weight: logs/checkpoints/gridae/mlpres_v2/256latent/best.ckpt

msdf:
  num_grids: ${msdf.num_grids}
  kernel_size: ${msdf.kernel_size}
  scale: ${msdf.scale}