name: GRIDAE
in_dim: ${add:1,${data.hand_cse_dim}}
kernel_size: ${msdf.kernel_size}
h_dims: 
  - 64
  - 128
  - 256
feat_dim: 64
obj_feat_dim: 64
res_h_dim: 128
n_res_layers: 2
out_dim: ${add:1,${data.hand_cse_dim}}
obj_in_dim: 1
pretrained_weight: logs/checkpoints/gridae/128latent/last-v1.ckpt

msdf:
  num_grids: ${msdf.num_grids}
  kernel_size: ${msdf.kernel_size}
  scale: ${msdf.scale}