name: GRIDAE
in_dim: ${add:1,${data.hand_cse_dim}}
kernel_size: ${msdf.kernel_size}
h_dims: 
  - 64
  - 128
  - 256
feat_dim: 128
obj_feat_dim: 128
res_h_dim: 128
n_res_layers: 3
out_dim: ${add:1,${data.hand_cse_dim}}
obj_in_dim: 1
pretrained_weight: logs/checkpoints/gridae/128latent/best-epoch=16-val/total_loss=0.0948.ckpt

msdf:
  num_grids: ${msdf.num_grids}
  kernel_size: ${msdf.kernel_size}
  scale: ${msdf.scale}