name: LGVQVAE
in_dim: ${add:1,${data.hand_cse_dim}}
h_dims: 
  - 32
  - 128
  - 256
  - 512
res_h_dim: 1024
n_res_layers: 4
n_embeddings: 128
embedding_dim: 1024
beta: 0.25
out_dim: ${add:1,${data.hand_cse_dim}}
obj_in_dim: 1