defaults:
  - msdf: sparse
  - data: grab_multi_contact
  - ae: gridae_128latent_v2
  - pose_optimizer: lg_base
  - _self_

contact_unit: "grid"
correspondence_type: "cse"

data:
  contact_unit: ${contact_unit}

train:
  batch_size: 32
  augment: false

val:
  batch_size: 32

test:
  n_processes: 20
  n_samples: 20
  batch_size: ${test.n_samples}


hydra:
  job:
    chdir: false
  run:
    dir: .
  output_subdir: null
  job_logging:
    disable_existing_loggers: false
  hydra_logging:
    disable_existing_loggers: false